name:                Metagen
version:             0.1.0.0
github:              "github.com/thautwarm/Metagen"
license:             BSD3
author:              "Taine Zhao"
maintainer:          "twshere@outlook.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point uers to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Metagen#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- template-haskell
- haskell-src-meta
- haskell-src-exts

library:
  source-dirs: src

default-extensions:
- ViewPatterns
- DeriveGeneric
- DeriveFunctor
- DeriveTraversable
- LambdaCase
- TemplateHaskell
- QuasiQuotes
- DuplicateRecordFields
- StandaloneDeriving
- ExistentialQuantification
- MultiParamTypeClasses
- NamedFieldPuns
- PartialTypeSignatures
- FlexibleInstances
- FlexibleContexts
- KindSignatures
- Rank2Types
- TypeApplications
- FunctionalDependencies
- PolyKinds
- UndecidableInstances

executables:
  Metagen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Metagen

tests:
  Metagen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Metagen
